### ISSUE TITLE
Looking for "Path_to_file.xls" from your "Data Input" Chapter (page 48)

### ISSUE THREAD

**Issue by Pearapon** [thomas-haslwanter/statsintro_python#4]
Dear Sir,

       I cannot find the file "path_to_file.xls" for testing with the code on page 48 (Data Input)

**Comment by thomas-haslwanter** [comment]
No file has been provided here, because any MS Excel file containing data would be fine.
In case you don't have Excel, I am attaching the file "ExcelData.xls" (in zipped form)
[ExcelData.zip](https://github.com/thomas-haslwanter/statsintro_python/files/935905/ExcelData.zip)
, which can be read with the command
```
xls = pd.ExcelFile('ExcelData.xls')


data = xls.parse()
```

**Comment by Pearapon** [comment]
Dear Thomas,

 

              Thank you very much

 

Best Regards

Pearapon S.

Bangkok, Thailand
